package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/spf13/cobra"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Configuration management",
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		// Config commands don't need an existing config file.
		return nil
	},
}

var (
	configInitAppID   int
	configInitAppHash string
	configInitPhone   string
)

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a configuration file with sensible defaults",
	Long:  "Outputs a complete TOML config to stdout. Redirect to a file: stenographer config init --app-id 123 --app-hash abc --phone +1234567890 > config.toml",
	RunE: func(cmd *cobra.Command, args []string) error {
		if configInitAppID == 0 {
			return fmt.Errorf("--app-id is required")
		}
		if configInitAppHash == "" {
			return fmt.Errorf("--app-hash is required")
		}
		if configInitPhone == "" {
			return fmt.Errorf("--phone is required")
		}

		configDir := filepath.Join(homeDir(), ".config", "stenographer")

		data := map[string]interface{}{
			"AppID":       configInitAppID,
			"AppHash":     configInitAppHash,
			"Phone":       configInitPhone,
			"SessionFile": filepath.Join(configDir, "session.json"),
			"DatabasePath": filepath.Join(configDir, "stenographer.db"),
		}

		return configTemplate.Execute(os.Stdout, data)
	},
}

func homeDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "~"
	}
	return home
}

var configTemplate = template.Must(template.New("config").Parse(`# Stenographer configuration file
# Generated by: stenographer config init

# Telegram API credentials
# Obtain from https://my.telegram.org/apps
[telegram]
app_id = {{.AppID}}
app_hash = "{{.AppHash}}"
phone = "{{.Phone}}"
session_file = "{{.SessionFile}}"

# Database settings
# Path to the SQLite database file
[database]
path = "{{.DatabasePath}}"

# Logging configuration
# Levels: debug, info, warn, error
[logging]
level = "info"

# Chat filter settings
# mode: "blacklist" (log all except listed) or "allowlist" (log only listed)
[filter]
mode = "blacklist"
`))

func init() {
	rootCmd.AddCommand(configCmd)
	configCmd.AddCommand(configInitCmd)

	configInitCmd.Flags().IntVar(&configInitAppID, "app-id", 0, "Telegram App ID")
	configInitCmd.Flags().StringVar(&configInitAppHash, "app-hash", "", "Telegram App Hash")
	configInitCmd.Flags().StringVar(&configInitPhone, "phone", "", "Phone number in E.164 format (e.g., +1234567890)")
}
