// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type AppState struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ChannelAccessHash struct {
	UserID     int64 `json:"user_id"`
	ChannelID  int64 `json:"channel_id"`
	AccessHash int64 `json:"access_hash"`
}

type ChannelState struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
	Pts       int64 `json:"pts"`
}

type ChatFilter struct {
	ID         int64  `json:"id"`
	ChatID     int64  `json:"chat_id"`
	ChatType   string `json:"chat_type"`
	Identifier string `json:"identifier"`
	Note       string `json:"note"`
	CreatedAt  string `json:"created_at"`
}

type Message struct {
	ID            int64          `json:"id"`
	TelegramMsgID int64          `json:"telegram_msg_id"`
	ChatID        int64          `json:"chat_id"`
	ChatType      string         `json:"chat_type"`
	SenderID      sql.NullInt64  `json:"sender_id"`
	SenderType    sql.NullString `json:"sender_type"`
	MessageText   string         `json:"message_text"`
	Date          int64          `json:"date"`
	EditDate      sql.NullInt64  `json:"edit_date"`
	IsOutgoing    int64          `json:"is_outgoing"`
	ReplyToMsgID  sql.NullInt64  `json:"reply_to_msg_id"`
	MediaType     sql.NullString `json:"media_type"`
	RawJson       sql.NullString `json:"raw_json"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type UpdateState struct {
	UserID int64 `json:"user_id"`
	Pts    int64 `json:"pts"`
	Qts    int64 `json:"qts"`
	Date   int64 `json:"date"`
	Seq    int64 `json:"seq"`
}
