// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addChatFilter = `-- name: AddChatFilter :exec
INSERT OR REPLACE INTO chat_filters (chat_id, chat_type, identifier, note) VALUES (?, ?, ?, ?)
`

type AddChatFilterParams struct {
	ChatID     int64  `json:"chat_id"`
	ChatType   string `json:"chat_type"`
	Identifier string `json:"identifier"`
	Note       string `json:"note"`
}

func (q *Queries) AddChatFilter(ctx context.Context, arg AddChatFilterParams) error {
	_, err := q.db.ExecContext(ctx, addChatFilter,
		arg.ChatID,
		arg.ChatType,
		arg.Identifier,
		arg.Note,
	)
	return err
}

const getAppState = `-- name: GetAppState :one
SELECT value FROM app_state WHERE key = ?
`

func (q *Queries) GetAppState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getChannelAccessHash = `-- name: GetChannelAccessHash :one
SELECT access_hash FROM channel_access_hash WHERE user_id = ? AND channel_id = ?
`

type GetChannelAccessHashParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) GetChannelAccessHash(ctx context.Context, arg GetChannelAccessHashParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChannelAccessHash, arg.UserID, arg.ChannelID)
	var access_hash int64
	err := row.Scan(&access_hash)
	return access_hash, err
}

const getChannelPts = `-- name: GetChannelPts :one
SELECT pts FROM channel_state WHERE user_id = ? AND channel_id = ?
`

type GetChannelPtsParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) GetChannelPts(ctx context.Context, arg GetChannelPtsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChannelPts, arg.UserID, arg.ChannelID)
	var pts int64
	err := row.Scan(&pts)
	return pts, err
}

const getUpdateState = `-- name: GetUpdateState :one
SELECT pts, qts, date, seq FROM update_state WHERE user_id = ?
`

type GetUpdateStateRow struct {
	Pts  int64 `json:"pts"`
	Qts  int64 `json:"qts"`
	Date int64 `json:"date"`
	Seq  int64 `json:"seq"`
}

func (q *Queries) GetUpdateState(ctx context.Context, userID int64) (GetUpdateStateRow, error) {
	row := q.db.QueryRowContext(ctx, getUpdateState, userID)
	var i GetUpdateStateRow
	err := row.Scan(
		&i.Pts,
		&i.Qts,
		&i.Date,
		&i.Seq,
	)
	return i, err
}

const isChatFiltered = `-- name: IsChatFiltered :one
SELECT count(*) FROM chat_filters WHERE chat_id = ?
`

func (q *Queries) IsChatFiltered(ctx context.Context, chatID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isChatFiltered, chatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChannelStates = `-- name: ListChannelStates :many
SELECT channel_id, pts FROM channel_state WHERE user_id = ?
`

type ListChannelStatesRow struct {
	ChannelID int64 `json:"channel_id"`
	Pts       int64 `json:"pts"`
}

func (q *Queries) ListChannelStates(ctx context.Context, userID int64) ([]ListChannelStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelStatesRow{}
	for rows.Next() {
		var i ListChannelStatesRow
		if err := rows.Scan(&i.ChannelID, &i.Pts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatFilters = `-- name: ListChatFilters :many
SELECT id, chat_id, chat_type, identifier, note, created_at FROM chat_filters ORDER BY created_at
`

func (q *Queries) ListChatFilters(ctx context.Context) ([]ChatFilter, error) {
	rows, err := q.db.QueryContext(ctx, listChatFilters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatFilter{}
	for rows.Next() {
		var i ChatFilter
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ChatType,
			&i.Identifier,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChatFilter = `-- name: RemoveChatFilter :exec
DELETE FROM chat_filters WHERE chat_id = ?
`

func (q *Queries) RemoveChatFilter(ctx context.Context, chatID int64) error {
	_, err := q.db.ExecContext(ctx, removeChatFilter, chatID)
	return err
}

const setAppState = `-- name: SetAppState :exec
INSERT OR REPLACE INTO app_state (key, value) VALUES (?, ?)
`

type SetAppStateParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetAppState(ctx context.Context, arg SetAppStateParams) error {
	_, err := q.db.ExecContext(ctx, setAppState, arg.Key, arg.Value)
	return err
}

const updateDate = `-- name: UpdateDate :execresult
UPDATE update_state SET date = ? WHERE user_id = ?
`

type UpdateDateParams struct {
	Date   int64 `json:"date"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) UpdateDate(ctx context.Context, arg UpdateDateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDate, arg.Date, arg.UserID)
}

const updateDateSeq = `-- name: UpdateDateSeq :execresult
UPDATE update_state SET date = ?, seq = ? WHERE user_id = ?
`

type UpdateDateSeqParams struct {
	Date   int64 `json:"date"`
	Seq    int64 `json:"seq"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) UpdateDateSeq(ctx context.Context, arg UpdateDateSeqParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDateSeq, arg.Date, arg.Seq, arg.UserID)
}

const updatePts = `-- name: UpdatePts :execresult
UPDATE update_state SET pts = ? WHERE user_id = ?
`

type UpdatePtsParams struct {
	Pts    int64 `json:"pts"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) UpdatePts(ctx context.Context, arg UpdatePtsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePts, arg.Pts, arg.UserID)
}

const updateQts = `-- name: UpdateQts :execresult
UPDATE update_state SET qts = ? WHERE user_id = ?
`

type UpdateQtsParams struct {
	Qts    int64 `json:"qts"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) UpdateQts(ctx context.Context, arg UpdateQtsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQts, arg.Qts, arg.UserID)
}

const updateSeq = `-- name: UpdateSeq :execresult
UPDATE update_state SET seq = ? WHERE user_id = ?
`

type UpdateSeqParams struct {
	Seq    int64 `json:"seq"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) UpdateSeq(ctx context.Context, arg UpdateSeqParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSeq, arg.Seq, arg.UserID)
}

const upsertChannelAccessHash = `-- name: UpsertChannelAccessHash :exec
INSERT OR REPLACE INTO channel_access_hash (user_id, channel_id, access_hash) VALUES (?, ?, ?)
`

type UpsertChannelAccessHashParams struct {
	UserID     int64 `json:"user_id"`
	ChannelID  int64 `json:"channel_id"`
	AccessHash int64 `json:"access_hash"`
}

func (q *Queries) UpsertChannelAccessHash(ctx context.Context, arg UpsertChannelAccessHashParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelAccessHash, arg.UserID, arg.ChannelID, arg.AccessHash)
	return err
}

const upsertChannelPts = `-- name: UpsertChannelPts :exec
INSERT OR REPLACE INTO channel_state (user_id, channel_id, pts) VALUES (?, ?, ?)
`

type UpsertChannelPtsParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
	Pts       int64 `json:"pts"`
}

func (q *Queries) UpsertChannelPts(ctx context.Context, arg UpsertChannelPtsParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelPts, arg.UserID, arg.ChannelID, arg.Pts)
	return err
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO messages (telegram_msg_id, chat_id, chat_type, sender_id, sender_type, message_text, date, edit_date, is_outgoing, reply_to_msg_id, media_type, raw_json, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT(telegram_msg_id, chat_id, chat_type)
DO UPDATE SET
    message_text = excluded.message_text,
    edit_date = excluded.edit_date,
    raw_json = excluded.raw_json,
    media_type = excluded.media_type,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertMessageParams struct {
	TelegramMsgID int64          `json:"telegram_msg_id"`
	ChatID        int64          `json:"chat_id"`
	ChatType      string         `json:"chat_type"`
	SenderID      sql.NullInt64  `json:"sender_id"`
	SenderType    sql.NullString `json:"sender_type"`
	MessageText   string         `json:"message_text"`
	Date          int64          `json:"date"`
	EditDate      sql.NullInt64  `json:"edit_date"`
	IsOutgoing    int64          `json:"is_outgoing"`
	ReplyToMsgID  sql.NullInt64  `json:"reply_to_msg_id"`
	MediaType     sql.NullString `json:"media_type"`
	RawJson       sql.NullString `json:"raw_json"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessage,
		arg.TelegramMsgID,
		arg.ChatID,
		arg.ChatType,
		arg.SenderID,
		arg.SenderType,
		arg.MessageText,
		arg.Date,
		arg.EditDate,
		arg.IsOutgoing,
		arg.ReplyToMsgID,
		arg.MediaType,
		arg.RawJson,
	)
	return err
}

const upsertUpdateState = `-- name: UpsertUpdateState :exec
INSERT OR REPLACE INTO update_state (user_id, pts, qts, date, seq) VALUES (?, ?, ?, ?, ?)
`

type UpsertUpdateStateParams struct {
	UserID int64 `json:"user_id"`
	Pts    int64 `json:"pts"`
	Qts    int64 `json:"qts"`
	Date   int64 `json:"date"`
	Seq    int64 `json:"seq"`
}

func (q *Queries) UpsertUpdateState(ctx context.Context, arg UpsertUpdateStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertUpdateState,
		arg.UserID,
		arg.Pts,
		arg.Qts,
		arg.Date,
		arg.Seq,
	)
	return err
}
